theme: jekyll-theme-tactile
repository: DanielKramer98/DanielKramer98.github.io
github: [metadata]
linkedIn: https://www.linkedin.com/in/daniel-kramer-8190b0143/
email: daniel@danielkramer.xyz
github1: https://github.com/drkspace
github2: https://github.com/drk98